### ISSUE TITLE
Add or describe a way to run ghcid for client and server code

### ISSUE THREAD

**Issue by voidus** [FPtje/miso-isomorphic-example#20]
GHCID has been so helpful in keeping feedback cycle times short, it would be great if we could show how to use it.

**Comment by FPtje** [comment]
Sorry for the late reply. I've thought about this suggestion, but decided to decline it.

This example is meant to show how isomorphism works with miso. I'd like to keep this example minimal, since I'm afraid people can be confused by fancy, but not strictly necessary things. This includes ghcid, but also tests, guides on setting up a Haskell environment, using servant, etc.

The more this example tries to explain, the less clear it will actually be. This repo is meant to show up on Google when people type in "Miso isomorphism", and for this to explain it to them most efficiently.

There's a fork/expansion [here](https://github.com/Tehnix/miso-isomorphic-stack) that does seem to take the full environment approach. It wouldn't be my choice, but I most certainly appreciate the variation.
