### ISSUE TITLE
Why Nix seems to be a hard dependency?

### ISSUE THREAD

**Issue by chespinoza** [FPtje/miso-isomorphic-example#21]
I'd like to say that it would be really good to add instructions without considering nix as a hard dependency in the dev flow, doing so you are excluding people which don't want to use Nix.
Thanks.

**Comment by FPtje** [comment]
Nix is a hard dependency because to me it was really easy to reliably get the example up and running for everyone. Nix really does make sure dependencies are available and working. Using e.g. stack is possible, but would have required more work on my end to get to work.

There seems to be an expanded isomorphic example, based on this one, using stack. Check it out here:
https://github.com/Tehnix/miso-isomorphic-stack

I'll mention it in the README.

**Comment by FPtje** [comment]
CC @Tehnix
